# This file is used by CI to get TwilioPlayer from the internal podspec repo. When TwilioPlayer 
# is publicly available we can add it to the main Podfile and delete this file.

source 'git@github.com:twilio/cocoapod-specs-internal.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks!
workspace 'LiveStream'

target 'LiveStream' do
  project 'LiveStream/LiveStream.xcodeproj'

  pod 'Alamofire', '~> 5'
  pod 'AmazonIVSPlayer', '1.3.3'
  pod 'AppCenter', '~> 4'
  pod 'DatadogSDK', '~> 1'
  pod 'InAppSettingsKit', '~> 3'
  pod 'KeychainAccess', '~> 4'
  pod 'SVProgressHUD', '~> 2'
  pod 'SwiftyUserDefaults', '~> 5'
  pod 'TwilioConversationsClient', '~> 1'
  pod 'TwilioPlayer', '1.0.0-rc33'
  pod 'TwilioVideo', '~> 4'
end
